export enum OrderStatus {
  CART = 'CART',
  CONFIRMED = 'CONFIRMED',
  PAID = 'PAID',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  ON_THE_WAY = 'ON_THE_WAY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
